export const LEGEND_ITEMS = {
  // --- COLOR LEGENDS ---
  HEAT_INDEX: {
    id: "heatIndex",
    label: "Heat Index",
    type: "color",
    category: "Weather Layers",
    interactive: false,
    colors: [
      { color: "#e6e6e6", description: "Not Hazardous" },
      { color: "#cc0001", description: "Caution" },
      { color: "#ff6600", description: "Extreme Caution" },
      { color: "#ffcc00", description: "Danger" },
      { color: "#ffff00", description: "Extreme Danger" },
    ],
    isActive: (appState) => appState.weatherLayer.type === "HeatIndex",
  },
  RAIN_VIEWER: {
    id: "rainViewer",
    label: "Rain Intensity",
    type: "color",
    category: "Weather Layers",
    interactive: false,
    colors: [
      { color: "#0324fc", description: "Overcast" },
      { color: "#0a9608", description: "Drizzle" },
      { color: "#dff20f", description: "Light Rain" },
      { color: "#fa980f", description: "Moderate Rain" },
      { color: "#d41706", description: "Show/Heavy Rain" },
    ],
    isActive: (appState) => appState.weatherLayer.type === "Rain",
  },
  LANDSLIDE: {
    id: "landslide",
    label: "Landslide Hazard",
    type: "color",
    category: "Hazard Mapping",
    interactive: false,
    colors: [
      { color: "#FFFF00", description: "Low Susceptibility" },
      { color: "#FFA500", description: "Moderate Susceptibility" },
      { color: "#FF4500", description: "High Susceptibility" },
    ],
    isActive: (appState) => appState.isHazardLayerActive.Landslide,
  },
  FLOOD_RISK: {
    id: "floodRisk",
    label: "Flood Risk",
    type: "color",
    category: "Hazard Mapping",
    interactive: false,
    colors: [
      { color: "#002474", description: "Very High Susceptibility to Flooding" },
      { color: "#5a00ff", description: "High Susceptibility to Flooding" },
      { color: "#b047ff", description: "Moderate Susceptibility to Flooding" },
      { color: "#e3d1ff", description: "Low Susceptibility to Flooding" },
      { color: "#ffffff", description: "None" },
    ],
    isActive: (appState) => appState.isHazardLayerActive.Flood,
  },
  STORM_SURGE: {
    id: "stormSurge",
    label: "Storm Surge",
    type: "color",
    category: "Hazard Mapping",
    interactive: false,
    colors: [
      { color: "#002474", description: "Very High Susceptibility to Flooding" },
      { color: "#5a00ff", description: "High Susceptibility to Flooding" },
      { color: "#b047ff", description: "Moderate Susceptibility to Flooding" },
      { color: "#e3d1ff", description: "Low Susceptibility to Flooding" },
      { color: "#ffffff", description: "None" },
    ],
    isActive: (appState) => appState.isHazardLayerActive.StormSurge,
  },

  // --- ICON SYMBOL LEGENDS ---
  HOSPITALS: {
    id: "hospitals",
    label: "Hospital",
    type: "symbol",
    category: "Emergency Agencies",
    interactive: true,
    icon: { name: "local-hospital", library: "MaterialIcons", color: "#333dff" },
    isActive: (appState) => appState.isFacilitiesLayerActive.Hospitals,
  },
  FIRE_STATIONS: {
    id: "fireStations",
    label: "Fire Station",
    type: "symbol",
    category: "Emergency Agencies",
    interactive: true,
    icon: { name: "fire-truck", library: "MaterialIcons", color: "#ff4e33" },
    isActive: (appState) => appState.isFacilitiesLayerActive.FireStations,
  },
  EVACUATION_CENTERS: {
    id: "evacCenters",
    label: "Evacuation Center",
    type: "symbol",
    category: "Emergency Agencies",
    interactive: true,
    icon: { name: "night-shelter", library: "MaterialIcons", color: "#754406" },
    isActive: (appState) => appState.isFacilitiesLayerActive.EvacSites,
  },
  USER_REPORTED_HAZARD: {
    id: "userReportedHazard",
    label: "User Reported Hazard",
    type: "symbol",
    category: "User Reports",
    interactive: true,
    icon: { name: "warning", library: "MaterialIcons", color: "#f09724" },

    isActive: (appState) => true,
  },
};
